---
on:
#  push:
#    branches:
#      - main
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5
        with:
          python-version: '3.10'

      - name: Update APIs
        run: |
          pip install -r requirements.txt
          python scraper.py

#      - name: Upload apis
#        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
#        with:
#          name: apis
#          path: nhs-digital/apis
#          retention-days: 1

      - name: Publish
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add nhs-digital/apis
          git diff-index --quiet HEAD || git commit -m 'Publish NHS apis'
          git push


#  publish:
#    runs-on: ubuntu-latest
#    if: ${{ github.ref == 'refs/heads/main' }}
#    needs: build
#    permissions:
#      contents: write
#    steps:
#      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
#
#      - name: Download apis file
#        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
#        with:
#          name: apis
#          path: temp-nhs-digital/apis
#
#      - name: Overwrite nhs apis
#        run: |
#          cat 'temp-nhs-digital/apis' > 'nhs-digital/apis'
#
#      - name: Publish
#        run: |
#          git config --global user.email "github-actions@github.com"
#          git config --global user.name "github-actions"
#          git add nhs-digital/apis
#          git commit -m 'Publish NHS apis'
#          git push
